name: Trigger Manifest Repo Sync

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the `main` branch

jobs:
  dispatch-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Manifest Repository Sync
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.MANIFEST_SYNC_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/jari-creator/manifest/dispatches \
            -d '{"event_type":"repo-updated"}'
